package com.whch.newspicker.mapper;


import com.whch.newspicker.entity.user;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface userMapper {
    /**

     *
     * 用户登录
     */
user userlogin(@Param("tel") String tel,@Param("password") String password);

    /**
     *
     * @param id
     * 注册用户
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int insertSelective(@Param("userBean") user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */

    int selectByPrimaryKey(String tel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(user record);

    List<user> userlist();
//    分页
    List<user> userlistlimit(@Param("fromNum")int fromNum,@Param("pageSize")int pageSize);
}