spring:

  datasource:
    url: jdbc:mysql://localhost:3306/netspider?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: rightanswer
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.whch.newspicker.entity

